import type { ContentType } from "@/types";

export interface HelpSectionLink {
  id: string;
  title: string;
}

type FrontmatterContentType = Extract<
  ContentType,
  "note" | "diary" | "project" | "roadmap" | "graph" | "doc"
>;

export interface FrontmatterHelpExample {
  id: string;
  navTitle: string;
  title: string;
  type: FrontmatterContentType;
  description: string;
  suitableFor: string;
  commonPatterns: string[];
  writingTips: string[];
  raw: string;
}

export const FRONTMATTER_FIELD_TABLE = [
  "| 类型 | 必填字段 | 可选字段 | 默认/回退行为 |",
  "| --- | --- | --- | --- |",
  "| note | `title` | `date/excerpt/tags` | `date` 默认为当天 |",
  "| project | `name/description/github` | `demo/date/tags/techStack` | 缺失时按字段默认空值处理 |",
  "| diary（考研日志） | `title/date` | `time/excerpt/tags/mood/weather/location/companions` | `time` 缺失时回退 `00:00` |",
  "| roadmap | `title/description` | `date/status` | `status` 非法值回退 `active` |",
  "| graph | `name` | `description/date` | 若无 `name` 会尝试读取 `title` |",
  "| doc | 无强制 | `title/date` | 无 frontmatter 也可渲染正文 |",
  "",
  "保存策略：仅正文改动时会尽量原样保留 frontmatter（包含注释/缩进/空行）。",
  "当元数据字段发生变化时会重新序列化 frontmatter（可能丢失注释与原始排版）。",
  "序列化会跳过 `undefined/null`；并保留常见空数组字段（`tags/companions/techStack`）以减少无意义 diff。",
].join("\n");

export const FRONTMATTER_WRITING_RULES = [
  "frontmatter 只放适合概括文档的元数据，例如标题、摘要、标签、发布日期；正文再展开细节与论证。",
  "优先让 frontmatter 与正文分工明确：标题/摘要回答“这篇是什么”，正文回答“为什么、怎么做、结果如何”。",
  "如果某个信息只在正文里出现一次，不要强行塞进 frontmatter；只有会被卡片、列表或头部展示消费的字段才值得放进去。",
  "先写最小 frontmatter 再补正文，比一开始堆很多字段更稳妥；不确定会不会长期维护的字段先不要引入。",
];

export const FRONTMATTER_FAQ = [
  "无 frontmatter 时会自动生成类型默认元数据，不影响正文编辑与预览。",
  "YAML 语法错误时会回退到默认元数据，但正文会继续保留并正常渲染。",
  "仅修改正文时会原样保留 frontmatter；修改元数据字段后会尽量在原 frontmatter 上做增量更新。",
  "`roadmap.status` 仅支持 `active/completed/paused`，非法值回退 `active`。",
  "`graph` 类型优先读取 `name`，缺失时会回退读取 `title`。",
  "`project.techStack` 适合写结构化技术栈，功能说明和实现细节仍应留在正文。",
];

export const FRONTMATTER_HELP_EXAMPLES: FrontmatterHelpExample[] = [
  {
    id: "frontmatter-note",
    navTitle: "note 写法",
    title: "note（学习笔记）",
    type: "note",
    description: "适合沉淀调研、教程、问题排查与知识总结。最常见结构是背景 -> 结论 -> 过程 -> 总结。",
    suitableFor:
      "当你希望读者先快速理解主题，再决定是否深入细节时，note 是最稳妥的写法。它尤其适合记录问题排查、知识整理、教程总结。",
    commonPatterns: [
      "先用 `excerpt` 概括主题，方便列表页快速判断是否值得点开。",
      "正文优先写 `问题背景` 或 `适用场景`，让读者知道这篇笔记解决什么问题。",
      "把最重要的结论提前成独立章节，例如 `核心结论`、`结论先行` 或 `关键结论`。",
    ],
    writingTips: [
      "标签只保留 2-4 个最稳定的关键词，不要把正文小节标题也都写成标签。",
      "如果内容明显是步骤教学，正文可以改成“前置条件 -> 步骤 -> 常见问题”的教程结构。",
      "排查类笔记建议保留失败尝试与最终根因，后续复盘价值比只写结论更高。",
    ],
    raw: [
      "---",
      "title: React 状态同步排查笔记",
      "date: 2026-04-03",
      "excerpt: 先写结论，再拆原因与修复步骤，是最常见也最容易复用的笔记写法。",
      "tags: [react, 调试, 前端]",
      "---",
      "",
      "## 问题背景",
      "",
      "最近在开发编辑器时，预览状态与工具栏状态出现了不同步的问题，症状是切换视图后按钮高亮没有立即更新。",
      "",
      "## 核心结论",
      "",
      "1. 先确认状态源头，避免多个组件各自维护同名状态。",
      "2. 把派生状态留在渲染层，不要重复写入 store。",
      "3. 修复后补一条回归测试，防止下一次重构回退。",
      "",
      "## 排查过程",
      "",
      "### 1. 复现条件",
      "",
      "- 在主编辑区切换预览模式",
      "- 再打开帮助面板",
      "- 返回后观察工具栏按钮状态",
      "",
      "### 2. 根因定位",
      "",
      "> [!TIP]",
      "> 笔记最常见的写法是“背景 -> 结论 -> 过程 -> 总结”，读者能最快抓到重点。",
      "",
      "经过比对发现，真正的视图状态保存在 store 中，但工具栏还维护了一份局部状态，导致两边更新时机不一致。",
      "",
      "## 总结",
      "",
      "这类笔记适合把结论放前面，把细节作为支撑材料写在后面，方便自己复盘，也方便后续整理成文章。",
    ].join("\n"),
  },
  {
    id: "frontmatter-diary",
    navTitle: "diary 写法",
    title: "diary（考研日志）",
    type: "diary",
    description: "适合记录当天目标、完成情况与复盘。最常见结构是目标 -> 完成情况 -> 问题复盘 -> 明日安排。",
    suitableFor:
      "当你需要按时间连续记录学习进度，并希望后续按天或按阶段回看状态变化时，diary 是最适合的类型。",
    commonPatterns: [
      "frontmatter 里补齐 `date/time/excerpt/tags`，方便时间线与列表页读取。",
      "正文先写 `今日目标`，再写 `完成情况`，这样复盘时能直接对照计划与结果。",
      "把当天最重要的失分点、拖延点或调整策略收敛到 `问题复盘`，方便后续按周总结。",
    ],
    writingTips: [
      "日记标题可以是主题化标题，不一定非要和日期重复；日期信息已经由 frontmatter 承担。",
      "如果一天有多条记录，建议 `excerpt` 只写最能代表该条内容的一句话，避免时间线里信息噪声过大。",
      "情绪、天气、地点这些字段适合用来做复盘上下文，不要把当天所有细节都塞进 frontmatter。",
    ],
    raw: [
      "---",
      "title: 4 月冲刺阶段复盘",
      "date: 2026-04-03",
      "time: 22:10",
      "excerpt: 今天完成英语真题两篇、政治选择题复盘，并整理了错题原因。",
      "tags: [考研, 英语, 政治]",
      "mood: steady",
      "weather: cloudy",
      "location: library",
      "companions: [solo]",
      "---",
      "",
      "## 今日目标",
      "",
      "- 完成英语阅读 2 篇",
      "- 复盘政治 1000 题错题",
      "- 整理明天要背的专业课提纲",
      "",
      "## 完成情况",
      "",
      "1. 英语阅读按时完成，第二篇正确率偏低。",
      "2. 政治错题主要集中在马原概念混淆。",
      "3. 专业课提纲只整理到一半，需要明天补完。",
      "",
      "## 问题复盘",
      "",
      "- 英语阅读失分点：定位句太慢，选项比对不够果断。",
      "- 政治复盘方式还可以更结构化，明天开始按知识点分类。",
      "- 晚上状态下滑明显，21:30 后不适合继续做新题。",
      "",
      "## 明日安排",
      "",
      "- 早上背政治高频概念 30 分钟",
      "- 下午补完专业课提纲",
      "- 晚上只做错题回顾，不再新开套题",
    ].join("\n"),
  },
  {
    id: "frontmatter-project",
    navTitle: "project 写法",
    title: "project（项目介绍）",
    type: "project",
    description: "适合写项目定位、亮点、技术栈与使用方式。最常见结构是定位 -> 亮点 -> 使用方式 -> 后续计划。",
    suitableFor:
      "当文档要被项目列表和详情页同时消费时，project 应该优先突出“这个项目是什么、解决什么问题、怎么试用”。",
    commonPatterns: [
      "frontmatter 里的 `name/description/github` 决定卡片与头部信息，必须写得简洁、可读。",
      "正文第一段先说明项目定位，避免一上来堆实现细节或开发故事。",
      "功能亮点用列表最清晰；技术栈放在 `techStack`，不要在正文重复罗列一遍相同信息。",
    ],
    writingTips: [
      "如果项目还没有 demo，宁可省略 `demo` 字段，也不要写无效占位链接。",
      "功能亮点只保留用户感知最强的 3-5 条，避免把开发待办写进展示文档。",
      "项目页正文更适合写“为什么做”和“怎么使用”，实现细节可以拆到 note 或 doc。",
    ],
    raw: [
      "---",
      "name: JasBlogEditor",
      "description: 用于本地编辑 JasBlog 内容并交给 GitHub Pages 自动部署的桌面编辑器。",
      "github: https://github.com/your-name/JasBlogEditor",
      "demo: https://example.com/editor-preview",
      "date: 2026-04-03",
      "tags: [tauri, react, markdown]",
      "techStack:",
      "  - name: Tauri 2",
      "    icon: Tauri",
      "  - name: React 19",
      "    icon: React",
      "  - name: TypeScript",
      "    icon: TS",
      "---",
      "",
      "## 项目定位",
      "",
      "JasBlogEditor 的目标不是做通用笔记软件，而是围绕 JasBlog 内容契约提供“编辑、预览、发布前自检”的专用工作流。",
      "",
      "## 功能亮点",
      "",
      "- 与 JasBlog 内容目录对齐，直接编辑 `content/` 下的 Markdown 文件",
      "- 内置 roadmap / graph / frontmatter 帮助示例，减少写作试错",
      "- 本地保存后即可提交到 GitHub，由 GitHub Pages 自动部署",
      "",
      "## 使用方式",
      "",
      "```bash",
      "npm run dev:app",
      "```",
      "",
      "启动后先选择 JasBlog 工作区，再按内容类型新建或编辑文档。",
      "",
      "## 后续计划",
      "",
      "- 完善帮助页示例文档",
      "- 继续统一编辑器与站点解析行为",
    ].join("\n"),
  },
  {
    id: "frontmatter-roadmap",
    navTitle: "roadmap 写法",
    title: "roadmap（规划文档）",
    type: "roadmap",
    description: "适合管理阶段目标和任务分解。最常见结构是先写规划说明，再用任务列表表达执行项。",
    suitableFor:
      "当你需要同时表达“为什么做这个计划”和“当前有哪些可执行任务”时，roadmap 最适合。正文说明和任务卡片会一起构成完整计划。",
    commonPatterns: [
      "frontmatter 负责计划标题、总描述与状态；任务明细放在正文里，用任务语法表达。",
      "正文开头先写一段规划说明，交代背景、目标或阶段边界，再进入任务列表。",
      "任务优先级写在行末反引号里，例如 `- [ ] 任务标题 `high``，不要写到标题前面。",
    ],
    writingTips: [
      "每个任务的 `描述` 建议只写一句话，真正的背景和限制放到 `详情` 下。",
      "如果任务没有明确结束时间，可以省略 `截止`，不要为了填字段而写虚假的日期。",
      "roadmap 适合看阶段推进，不适合记录长篇复盘；复盘更适合写成 note 或 diary。",
    ],
    raw: [
      "---",
      "title: 帮助页写作指南完善计划",
      "description: 为 frontmatter 分类补齐各类文档的完整示例与写作说明",
      "status: active",
      "date: 2026-04-03",
      "---",
      "",
      "先说明这个 roadmap 想解决什么，再列出任务。非任务文本会保留在正文区。",
      "",
      "## 任务列表",
      "",
      "- [-] 明确帮助页结构 `high`",
      "  描述: 确定 frontmatter 分类下需要展示哪些文档类型与说明层级",
      "  详情:",
      "    - 保留字段矩阵速查",
      "    - 增加写作通用规则",
      "    - 每类文档提供完整示例与写作建议",
      "",
      "- [ ] 抽离 frontmatter 示例模块 `high`",
      "  描述: 将各类示例内容从 HelpModal 拆到独立文件，降低维护成本",
      "  截止: 2026-04-05",
      "",
      "- [ ] 补充帮助页回归测试 `medium`",
      "  描述: 锁定章节目录与示例内容，避免后续改动时退化",
    ].join("\n"),
  },
  {
    id: "frontmatter-graph",
    navTitle: "graph 写法",
    title: "graph（图谱文档）",
    type: "graph",
    description: "适合用图结构解释概念关系。最常见结构是先说明图谱主题，再给出 `graph` 代码块与阅读提示。",
    suitableFor:
      "当你要表达节点之间的关系、层级或依赖，而不是线性步骤时，graph 比普通文档更直观。它适合知识结构、系统关系和概念网络。",
    commonPatterns: [
      "frontmatter 只概括图谱主题与说明，真正的图结构放在正文中的第一个 `graph` 代码块里。",
      "图谱前先用 1-2 段文字说明读图方式，帮助读者理解颜色、节点类别或连线含义。",
      "图谱后补一个 `阅读提示` 或 `如何使用` 小节，说明哪些节点最关键、如何从图中过渡到正文。",
    ],
    writingTips: [
      "JSON 至少保证 `nodes/edges` 结构正确，避免把帮助页示例写成无法渲染的图谱。",
      "节点标签保持短句，不要把整段说明塞进 `label`，复杂解释应放在正文。",
      "如果图谱内容本身就很复杂，正文应先给阅读入口，不要让用户一打开就直接面对大图。",
    ],
    raw: [
      "---",
      "name: 前端渲染能力图谱",
      "description: 用图谱梳理 Markdown 渲染、frontmatter 与特殊块语法之间的关系",
      "date: 2026-04-03",
      "---",
      "",
      "先用一段文字说明图谱想表达什么，再给出 `graph` 代码块，是图谱类文档最常见的写法。",
      "",
      "```graph",
      "{",
      '  "nodes": [',
      "    {",
      '      "id": "frontmatter",',
      '      "position": { "x": 80, "y": 80 },',
      '      "data": {',
      '        "label": "Frontmatter",',
      '        "color": "blue",',
      '        "edgeColor": "p1",',
      '        "tags": ["元数据"]',
      "      }",
      "    },",
      "    {",
      '      "id": "body",',
      '      "position": { "x": 340, "y": 80 },',
      '      "data": {',
      '        "label": "正文内容",',
      '        "color": "green",',
      '        "tags": ["Markdown"]',
      "      }",
      "    },",
      "    {",
      '      "id": "preview",',
      '      "position": { "x": 220, "y": 240 },',
      '      "data": {',
      '        "label": "预览结果",',
      '        "color": "orange",',
      '        "tags": ["渲染"]',
      "      }",
      "    }",
      "  ],",
      '  "edges": [',
      '    { "id": "e1", "source": "frontmatter", "target": "preview", "label": "影响头部信息" },',
      '    { "id": "e2", "source": "body", "target": "preview", "label": "影响正文渲染" }',
      "  ]",
      "}",
      "```",
      "",
      "## 阅读提示",
      "",
      "- 蓝色节点表示元数据层",
      "- 绿色节点表示正文渲染层",
      "- 连线表示谁影响谁",
    ].join("\n"),
  },
  {
    id: "frontmatter-doc",
    navTitle: "doc 写法",
    title: "doc（普通文档）",
    type: "doc",
    description: "适合说明文、规范文档和内部手册。最常见结构是适用范围 -> 操作步骤 -> 注意事项。",
    suitableFor:
      "当内容主要面向本地编辑、团队协作或流程说明，而不依赖站点的内容卡片体系时，doc 是最直接、约束最少的类型。",
    commonPatterns: [
      "doc 可以不写 frontmatter，但如果文档会长期维护，建议至少保留 `title/date`，便于归档和回看。",
      "正文优先围绕使用场景与步骤展开，而不是像 project 一样强调对外展示信息。",
      "如果文档本质是内部规范，使用 `适用范围 -> 操作步骤 -> 注意事项` 会比散文式写法更稳定。",
    ],
    writingTips: [
      "一份 doc 只解决一件事，避免把规范、复盘、教程和决策记录都混在同一篇里。",
      "如果文档更偏知识沉淀或问题总结，改写成 note 往往更适合后续检索与引用。",
      "步骤型文档尽量使用编号列表，后续增删步骤时 diff 更清晰。",
    ],
    raw: [
      "---",
      "title: 编辑器帮助页维护说明",
      "date: 2026-04-03",
      "---",
      "",
      "## 适用范围",
      "",
      "这类 doc 适合写通用说明、操作流程、内部规范，不要求站点卡片化展示。",
      "",
      "## 操作步骤",
      "",
      "1. 先更新 frontmatter 示例文档。",
      "2. 再检查对应预览是否仍与站点一致。",
      "3. 最后运行测试与构建验证。",
      "",
      "## 注意事项",
      "",
      "- `doc` 类型可以没有 frontmatter，但有标题和日期时更利于整理。",
      "- 当内容偏教程或总结时，也可以考虑改写为 note。",
    ].join("\n"),
  },
];

export const FRONTMATTER_SECTION_LINKS: HelpSectionLink[] = [
  { id: "frontmatter-support", title: "说明" },
  { id: "frontmatter-fields", title: "字段矩阵速查" },
  { id: "frontmatter-writing-rules", title: "写作通用规则" },
  ...FRONTMATTER_HELP_EXAMPLES.map((example) => ({
    id: example.id,
    title: example.navTitle,
  })),
  { id: "frontmatter-faq", title: "解析注意事项" },
];
